---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "capsule-rancher-addon.fullname" . }}-mutating-webhook-configuration
  labels:
    {{- include "capsule-rancher-addon.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.certManager.generateCertificates }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "capsule-rancher-addon.fullname" . }}-webhook-cert
  {{-  end }}
  {{- with .Values.customAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
{{- if not .Values.certManager.generateCertificates }}
      caBundle: Cg==
{{- end }}
      service:
        name: {{ include "capsule-rancher-addon.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /configmap
        port: {{ .Values.manager.webhook.service.port }}
    failurePolicy: {{ .Values.manager.webhook.failurePolicy }}
    name: configmap.rancher.addon.capsule-rancher-addon.clastix.io
    reinvocationPolicy: {{ .Values.manager.webhook.reinvocationPolicy }}
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - configmaps
    sideEffects: {{ .Values.manager.webhook.sideEffects }}
    timeoutSeconds: {{ .Values.manager.webhook.timeoutSeconds }}

